site_name: Loop Docs
theme: flatly
google_analytics: ['UA-109876065-1', 'loopkit.github.io']
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- 'index.md'
- Setup:
    - 'FAQs': 'setup/FAQs.md'
    - 'Insulin Pump': 'setup/requirements/pump.md'
    - 'CGM': 'setup/requirements/cgm.md'
    - 'RileyLink': 'setup/requirements/rileylink.md'
    - 'Computer': 'setup/requirements/computer.md'
    - 'iPhone': 'setup/requirements/iphone.md'
    - 'Apple Developer': 'setup/requirements/appledev.md'
- Build:
    - Overview: 'build/overview.md'
    - Setup Computer: 'build/build-computer.md'
    - Setup Developer Account: 'build/build-developer.md'
    - Setup Xcode: 'build/build-xcode.md'
    - Build Loop: 'build/build-loop.md'
    - Build Errors: 'build/build_errors.md'
    - Code Customization: 'build/code_customization.md'
    - New iPhone: 'build/new-iphone.md'
    - 'Update Loop':
        - 'New Version Info': 'build/update/new-version.md'
        - 'Update Loop': 'build/update/updating.md'
- Operation:
    - App setup:
        - 'Loop Settings': 'setup/loop-settings/settings.md'
        - 'Loop Services': 'setup/loop-settings/services.md'
        - 'RileyLink menu': 'setup/loop-settings/rileylink_menu.md'
        - 'Pump Setup': 'setup/loop-settings/pump.md'
        - 'Loop Displays': 'operation/overview.md'
    - How to Use Loop App:
        - 'Carb Entries': 'operation/features/carbs.md'
        - 'Bolus': 'operation/features/bolus.md'
        - 'Workout Targets': 'operation/features/workout.md'
        - 'Using ICE info': 'operation/features/ice.md'
        - 'Apple Watch': 'operation/features/watch.md'
        - 'iPhone widget': 'operation/features/widget.md'
        - 'Health App': 'operation/features/healthapp.md'
        - 'Loop Notifications': 'operation/features/notifications.md'
        - 'Pump Battery': 'operation/features/battery.md'
    - 'Looping Tips':
        - 'Open Loop': 'operation/loop/open-loop.md'
        - 'Closed Loop': 'operation/loop/close-loop.md'
    - Algorithm:
        - 'Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp-basal.md'
- Troubleshooting:
    - 'Overview': 'troubleshooting/overview.md'
    - 'Grey Loop': 'troubleshooting/green-loop.md'
    - 'Yellow/Red Loop': 'troubleshooting/yellow-red-loop.md'
    - 'Priming and Sites': 'troubleshooting/priming.md'
    - 'RileyLink': 'troubleshooting/rileylink.md'
    - 'Time Changes': 'troubleshooting/time-change.md'
    - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'NS Stopped Working': 'nightscout/mlab_cleanup.md'
    - 'Azure to Heroku': 'nightscout/azure_migration.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
